### PR TITLE
Add Atomic Design in Frontend Development

### PR DESCRIPTION
**Pull request by ccocoual**
The Atomic Design architecture proposed by Brad Frost is well adaptable to current frontend frameworks aka Angular, React, Vue, Polymer and more largely Web components.
It specifies how to split components to make them reusable and isolated.
Feel free to complete this PR or comment it.

### CODE REVIEW

**Comment by DovAmir** [comment]
this looks like a great design pattern, but every link in this list should hold a collection of several design patterns and not one pattern.
A resource on atomic design vs other design systems would be a good "design patterns" resource

**Comment by DovAmir** [comment]
you can add this instead http://getbem.com/introduction/   it contains different patterns and approaches

**Comment by DovAmir** [comment]
added link that mentions atomic

**Comment by ccocoual** [comment]
Sorry, I was quite busy last few days. 
I have searched for some resources that compare Atomic Design to other patterns but haven't found any. Concerning the getbem link, it is more a CSS approach when Atomic Design is about a way to separate components for a better separation of concerns and reusability.
If I find any resource that makes the comparison I will re-open this PR.
Thanks

**Pull request closed without merging**
