### PR TITLE
Add section for machine learning

### PR DESCRIPTION
**Pull request by terrytangyuan**
The current list is missing the machine learning category.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Hi @DovAmir Would you mind taking a look at this? Thanks!

**Comment by terrytangyuan** [comment]
@DovAmir Could you take a look? Thanks!

**Comment by terrytangyuan** [comment]
Friendly ping. Thanks!

**Comment by Jasminesarah210** [comment]
[Nice Addition](https://barigroupinc.com/)

**Pull request merged**
